####################################### Services
services:
  service-postgresql:
    image: ahmettoguz/postgres:17
    container_name: container-postgresql
    volumes:
      - volume-postgresql:/var/lib/postgresql/data
    env_file:
      - ./.env
    networks:
      - network-database
    restart: ${RESTART_POLICY}
    # ports:
    #   - 5432:5432

####################################### Networks
networks:
  network-database:
    external: true

####################################### Volumes
volumes:
  volume-postgresql:
    name: volume-postgresql
