####################################### Services
services:
  postgresql:
    image: ahmettoguz/postgres:17
    container_name: database-postgresql-c
    volumes:
      - ./mount:/var/lib/postgresql/data
    env_file:
      - ./.env
    networks:
      - network-database
    restart: ${RESTART_POLICY}
    # ports:
    #   - 5432:5432

####################################### Networks
networks:
  network-database:
    external: true
